# -*- coding: utf-8 -*-
"""DataCleaner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y5gSeRBnkp_sRp----IZHxAIDH1O2dYq
"""

#
# This notebook was used to to extract only the needed pieces of information 
# from the raw lichess dataset.
#
# SAMPLE OF INTENDED INPUT FOR EACH LINE
#     GameMode Result WhiteElo BlackElo Opening
#
import time

f = open("lichess_db_standard_rated_2013-01.pgn", "r")
outty = open("formatedLichessDatatest.txt", "a")

line = ""
num = 0

start = time.time()
for x in f:
  lines = ""
  if (x[1:6:1] == "Event"):
    line = x[8:-8:1]
  elif (x[1:7:1] == "Result"):
    line = line + "=" + x[9:-3:1]
  elif (x[1:9:1] == "WhiteElo"):
    line = line + "=" + x[11:-3:1]
  elif (x[1:9:1] == "BlackElo"):
    line = line + "=" + x[11:-3:1]
  elif (x[1:8:1] == "Opening"):
    line = line + "=" + x[10:-3:1]
    lines = line
    outty.write(lines + "\n")

outty.close()

time.sleep(1)
end = time.time()
print("Run Time: " , end-start)
